PMT_DotNet/Web/Controllers/TaskController.cs
using Data.Models;
using Domain.Entities;
using Newtonsoft.Json;
using Service;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Helper;
using Web.Models;

namespace Web.Controllers
{
    public class TaskController : Controller
    {
        TaskService taskservice = null;
        public TaskController()
        {
            taskservice = new TaskService();
        }
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AllTasks(int idProject )
        {

            var idP = Session["idProject"] as List<int>;
            
            if (idP == null)
            {
                idP = new List<int>();
            }
            
            Session["idProject"] = idP;
            var x = taskservice.DisplayTasksByProject(idProject);
            idP.Add(idProject);

            return View(x);
        }

        // GET: ReservationEvent/Create
        public ActionResult Create()
        {
            var idP = Session["idProject"] as List<int>;
            List<string> ListState = new List<string> { "ToDo", "Doing", "Done" };
            ViewBag.x = ListState.ToSelectItem();

            TaskModel taskmodel = new TaskModel();
            taskmodel.projectname= taskservice.FindNameProjectById(idP.First());
          
            return View(taskmodel);
        }


        // POST: ReservationEvent/Create
        [HttpPost]
        public ActionResult Create(TaskModel taskmodel)
        {
            var idP = Session["idProject"] as List<int>;
            taskmodel.idProject=idP.First();

            task taskToAdd = new task
            {
                Description=taskmodel.Description,
                idProject=taskmodel.idProject,
                id_user=taskmodel.id_user,
                DeadLine=taskmodel.DeadLine,
                StartDate=taskmodel.StartDate,
                state=taskmodel.state
            };



            taskservice.Add(taskToAdd);
            taskservice.commit();
            taskservice.Dispose();

           
           return RedirectToAction("AllTasks", new { idProject = idP.First() });
        }

        //GET: ReservationEvent/Edit/5
        public ActionResult Edit(int idProject, string description, int idUser)
        { 
            task taskToEdit = taskservice.FindTaskByPk(description);
            //TaskModel taskmodel = new TaskModel
            //{
            //    Description = taskToEdit.Description,
            //    idProject = taskToEdit.idProject,
            //    id_user = taskToEdit.id_user,
            //    DeadLine = taskToEdit.DeadLine,
            //    StartDate = taskToEdit.StartDate,
            //    state = taskToEdit.state

            //};

            return View(taskToEdit);

        }
        // POST: ReservationEvent/Edit/5
        [HttpPost]
        public ActionResult Edit(int idProject, string description, int idUser, task Task)
        {
            var idP = Session["idProject"] as List<int>;
            //task taskToEdit = taskservice.FindTaskByPk(Task.Description);
            task taskToEdit = new task { Description = Task.Description, idProject = Task.idProject, DeadLine = Task.DeadLine, StartDate = Task.StartDate, state = Task.state, id_user = Task.id_user };

            try
            {
                taskservice.Update(taskToEdit);
                //UpdateModel(taskToEdit);
            

                taskservice.commit();
                return RedirectToAction("AllTasks", new { idProject = idP.First() });


            }
            catch
            {


                return RedirectToAction("AllTasks", new { idProject = idP.First() }); 
            }


        }


        // GET: ReservationEvent/Delete/5
        public ActionResult Delete(string description)
        {
            task taskToDelete = taskservice.FindTaskByPk(description);
            if (taskToDelete == null)
            {
                return HttpNotFound();
            }
            TaskModel taskmodel = new TaskModel
            {
               Description= taskToDelete.Description,
               idProject= taskToDelete.idProject,
                id_user = taskToDelete.id_user,
                DeadLine = taskToDelete.DeadLine,
                StartDate = taskToDelete.StartDate,
                state = taskToDelete.state


            };

            return View(taskToDelete);
        }

        // POST: ReservationEvent/Delete/5
        [HttpPost]
        public ActionResult Delete(string description, TaskModel taskmodel)
        {
            var idP = Session["idProject"] as List<int>;
            task taskToDelete = taskservice.FindTaskByPk(description);
            taskservice.DeleteTask(taskToDelete.Description);
            taskservice.commit();
            taskservice.Dispose();


            return RedirectToAction("AllTasks", new { idProject = idP.First() });

        }

        public ActionResult taskStat(int idProject)
       {

            string projectName = taskservice.FindNameProjectById(idProject);
            string DeadlineInfo = taskservice.projectDeadlineVerification(idProject);
           // prepare a 2d array in c#
          ArrayList header = new ArrayList { "Task State", "Number" };
          ArrayList data1 = new ArrayList { "Doing", taskservice.numberOfAccomplishTasksByProject(idProject) };
          ArrayList data2 = new ArrayList { "Done", taskservice.numberOfInProgressTasksByProject(idProject) };
          ArrayList data3 = new ArrayList { "To Do", taskservice.numberOfNotStartedTasksByProject(idProject) };
          ArrayList data = new ArrayList { header, data1, data2, data3 };
           // convert it in json
          string dataStr = JsonConvert.SerializeObject(data, Formatting.None);
           // store it in viewdata/ viewbag
          ViewBag.Data = new HtmlString(dataStr);
          ViewData["projectname"] = projectName;
          ViewData["DeadlineInfo"] = DeadlineInfo;
            return View();
        }

        public ActionResult globalView()
        {
            

            return View();
        }


}
}

PMT_DotNet/Web/Controllers/projectController.cs
using Domain.Entities;
using Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using Data.Models;

namespace Web.Controllers
{
    public class projectController : Controller, IDisposable
    {

        ProjectService Pservice = null;
        CategoryService Cservice = null;
        ClientService CLservice = null;
        TeamService Tservice = null;


        public projectController()
        {
            Pservice = new ProjectService();
            Cservice = new CategoryService();
            CLservice = new ClientService();
            Tservice = new TeamService();

        }


        // GET: project
        public ActionResult AllProject()
        {
            var project = Pservice.GetMany();

            List<project> pr = new List<project>();
            foreach (var item in project)
            {
                pr.Add(
                    new project
                    {
                        IdProject = item.IdProject,
                        Description = item.Description,
                        Name = item.Name,
                        Priority = item.Priority,
                        Type = item.Type,
                        EndDate = item.EndDate,
                        StartDate = item.StartDate,
                        DocumentsUrl = item.DocumentsUrl

                    });

            }


            return View(pr);
        }




        [HttpPost]

        public ActionResult AllProject(String search)
        {
            var projects = Pservice.GetMany(p => p.Name == search);
            List<project> pr = new List<project>();
            List<category> cl = new List<category>();
            foreach (var item in projects)
            {
                pr.Add(
                    new project
                    {
                        IdProject = item.IdProject,
                        Description = item.Description,
                        Name = item.Name,
                        Priority = item.Priority,
                        Type = item.Type,
                        EndDate = item.EndDate,
                        StartDate = item.StartDate,
                        DocumentsUrl = item.DocumentsUrl

                    });


            }


            return View(pr);

        }


        public ActionResult Index()
        {

            return View();
        }




        // GET: project/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            project p = Pservice.GetById(id);




            if (p == null)
            {
                return HttpNotFound();
            }
            return View(p);

        }

        // GET: project/Create
        public ActionResult Create()
        {
            var categories = Cservice.GetMany(); ;
            var clients = CLservice.GetMany();
            var teams = Tservice.GetMany();
            ViewBag.category = new SelectList(categories, "IdCategory", "Name");
            ViewBag.client = new SelectList(clients, "IdClient", "Name");
            ViewBag.team = new SelectList(teams, "id_team", "nom_team");
            return View();
        }

        // POST: project/Create
        [HttpPost]
        public ActionResult Create(project p, HttpPostedFileBase doc)
        {

            if (!ModelState.IsValid || doc == null || doc.ContentLength == 0)
            {
                RedirectToAction("Create");
            }

            //if (doc != null  )
            //{
            //    //p.DocumentsUrl = doc.FileName;
            //    project pr = new project
            //    {
            //        IdProject = p.IdProject,
            //        Description = p.Description,
            //        Name = p.Name,
            //        Priority = p.Priority,
            //        Type = p.Type,
            //        EndDate = p.EndDate,
            //        StartDate = p.StartDate,
            //        DocumentsUrl = p.DocumentsUrl ,
            //        Category_IdCategory = p.Category_IdCategory ,
            //        id_client = p.id_client ,
            //        id_team = p.id_team

            //    };
            //    Pservice.Add(pr);
            //    Pservice.commit();
            //    Pservice.Dispose();
            //    // Sauvgarde de l'image

            //    var path = Path.Combine(Server.MapPath("~/Content/Upload/"), doc.FileName);
            //    doc.SaveAs(path);
            //    return RedirectToAction("Index");

            //}
            //return View();

            if (!ModelState.IsValid)
            {
                return Create();
            }


            p.DocumentsUrl = doc.FileName;
            project pr = new project
            {
                IdProject = p.IdProject,
                Description = p.Description,
                Name = p.Name,
                Priority = p.Priority,
                Type = p.Type,
                EndDate = p.EndDate,
                StartDate = p.StartDate,
                DocumentsUrl = p.DocumentsUrl,
                Category_IdCategory = p.Category_IdCategory,
                id_client = p.id_client,
                id_team = p.id_team

            };
            Pservice.Add(pr);
            Pservice.commit();
            Pservice.Dispose();
            var path = Path.Combine(Server.MapPath("~/Content/Upload/"), doc.FileName);
            doc.SaveAs(path);

            return RedirectToAction("Index");

        }

        // GET: project/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            project p = Pservice.GetById(id);

            if (p == null)
            {
                return HttpNotFound();
            }
            return View(p);
        }

        // POST: project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, project p)
        {
            if (!ModelState.IsValid)
            {
                return EditDetails();
            }

            if (ModelState.IsValid)
            {

                Pservice.Update(p);
                Pservice.commit();
                Pservice.Dispose();

                return RedirectToAction("Index");
            }
            return View(p);
        }

        // GET: project/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            project p = Pservice.GetById(id);

            if (p == null)
            {
                return HttpNotFound();
            }
            return View(p);
        }

        // POST: project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, project p)
        {
            Pservice.Delete(p);
            Pservice.commit();
            Pservice.Dispose();

            return RedirectToAction("Index");

        }
        public ActionResult EditDetails()
        {
            var categories = Cservice.GetMany(); ;
            var clients = CLservice.GetMany();
            var teams = Tservice.GetMany();
            ViewBag.category = new SelectList(categories, "IdCategory", "Name");
            ViewBag.client = new SelectList(clients, "IdClient", "Name");
            ViewBag.team = new SelectList(teams, "id_team", "nom_team");
            return View();

        }


        public ActionResult UploadFile(HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                string path = Server.MapPath("~/Files/" + file.FileName); // location
                file.SaveAs(path);
                @ViewBag.Path = path;




            }
            return View();



        }

        public ActionResult ExportPDF()


        {


            return new ActionAsPdf("index")
            {

                FileName = Server.MapPath("~/Content/Files/products.pdf")
            };
        }
        public ActionResult Chat()
        {
            return View();
        }



        public ActionResult ActiveList()
        {
            var project = Pservice.ActiveProject();

            List<project> pr = new List<project>();
            foreach (var item in project)
            {
                pr.Add(
                    new project
                    {
                        IdProject = item.IdProject,
                        Description = item.Description,
                        Name = item.Name,
                        Priority = item.Priority,
                        Type = item.Type,
                        EndDate = item.EndDate,
                        StartDate = item.StartDate,
                        DocumentsUrl = item.DocumentsUrl

                    });

            }


            return View(pr);
        }

        public ActionResult PassedList()
        {
            var project = Pservice.PassedProject();

            List<project> pr = new List<project>();
            foreach (var item in project)
            {
                pr.Add(
                    new project
                    {
                        IdProject = item.IdProject,
                        Description = item.Description,
                        Name = item.Name,
                        Priority = item.Priority,
                        Type = item.Type,
                        EndDate = item.EndDate,
                        StartDate = item.StartDate,
                        DocumentsUrl = item.DocumentsUrl

                    });

            }


            return View(pr);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Pservice.Dispose();
            }

PMT_DotNet/Web/Views/project/ActiveList.cshtml
@model IEnumerable<Domain.Entities.project>

@{
    ViewBag.Title = "ActiveList";
}

<h2>ActiveList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (Model != null)
{


    <div class="row mt">
        <div class="col-md-12">
            <div class="content-panel">
                <table class="table table-striped table-advance table-hover">
                    <h4><i class="fa fa-angle-right"></i> List Of Projects</h4>
                    <hr>
                    <thead>
                        <tr>


                            <th><i class="fa fa-bookmark"></i> Project Name </th>





                            <th></th>
                        </tr>
                    </thead>

                    @foreach (var item in Model)
                    {
                        <tbody>
                            <tr>
                                <td><a href="basic_table.html#">@Html.DisplayFor(modelItem => item.Name)</a></td>


                                <td>
                                    <a href="@Url.Action("Edit"  , new { id = item.IdProject })">

                                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                                    </a>

                                    <a href="@Url.Action("Delete"  , new { id = item.IdProject })">

                                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>


                                    </a>

                                    <a href="@Url.Action("Details"  , new { id = item.IdProject})">

                                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                                    </a>


                                    <a href="@Url.Action("AllTasks" ,"Task" , new { idProject = item.IdProject})">

                                        <span class="label label-info label-mini">Tasks</span>
                                    </a>
                                </td>
                            </tr>




                        </tbody>
                    }


                </table>

            </div>
        </div>
    </div>



}
<a href="@Url.Action("ExportPDF" , "project")">
    <button type="button" class="btn btn-primary btn-lg btn-block">Export PDF</button>
</a>

PMT_DotNet/Web/Views/project/Create.cshtml
@model Domain.Entities.project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "project", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })




        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "datefield" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "datefield" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Priority, new SelectList(new[] { "Normal", "Urgent", "Delayed" }), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority)
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, new SelectList(new[] { "General", "Web Design", "Construction", "Property Management", "Others" }), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_IdCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_IdCategory, (SelectList)ViewData["category"], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category_IdCategory)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.id_team, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.id_team, (SelectList)ViewData["team"], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_team)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_client, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.id_client, (SelectList)ViewData["client"], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_client)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentsUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("doc", null, new { type = "file" })
                @Html.ValidationMessageFor(model => model.DocumentsUrl)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PMT_DotNet/Web/Views/project/Delete.cshtml
@model Domain.Entities.project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdProject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdProject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>




    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdProject)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PMT_DotNet/Web/Views/project/Details.cshtml
@model Domain.Entities.project
@{string path = "~/Content/Upload/" + @Model.DocumentsUrl;}

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdProject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdProject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentsUrl)
        </dt>

        <dd>
            <a alt="Produit" href="@Url.Content(path)">@Model.DocumentsUrl</a>
        </dd>







    </dl>
</div>
<!-- LikeBtn.com BEGIN -->
<span class="likebtn-wrapper" data-identifier="item_1"></span>
<script>(function(d,e,s){if(d.getElementById("likebtn_wjs"))return;a=d.createElement(e);m=d.getElementsByTagName(e)[0];a.async=1;a.id="likebtn_wjs";a.src=s;m.parentNode.insertBefore(a, m)})(document,"script","//w.likebtn.com/js/w/widget.js");</script>
<!-- LikeBtn.com END -->


<a href="@Url.Action("Edit" , "project" ,  new { id = Model.IdProject })">

    <button type="button" class="btn btn-round btn-warning">EDIT</button>
</a>

<a href="@Url.Action("Index" , "project")">
    <button type="button" class="btn btn-round btn-danger">Back To List</button>
</a>

PMT_DotNet/Web/Views/project/Index.cshtml
@model IEnumerable<Domain.Entities.project>


@{
    ViewBag.Title = "Projects";
}
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<a href="@Url.Action("AllProject" , "project")">
    <button type="button" class="btn btn-primary btn-lg btn-block">All Projects</button>
</a>

<br />
<br />
<a href="@Url.Action("ActiveList" , "project")">
    <button type="button" class="btn btn-primary btn-lg btn-block">Active Projects</button>
</a>
<br />
<br />
<a href="@Url.Action("PassedList" , "project")">
    <button type="button" class="btn btn-primary btn-lg btn-block">Passed Projects</button>
</a>

PMT_DotNet/Web/Views/project/Map.cshtml
@using Jmelosegui.Mvc.GoogleMap

@{
    ViewBag.Title = "Map";
}

<h2>Map</h2>

@(
        Html.GoogleMap()
            .Name("map")
            .Height(500)
            .Markers(m => m.Add().Title("Hello World!"))
)


@section scripts
    {
    @(Html.GoogleMap().ScriptRegistrar())
}

PMT_DotNet/Web/Views/project/PassedList.cshtml
@model IEnumerable<Domain.Entities.project>

@{
    ViewBag.Title = "PassedList";
}

<h2>PassedList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (Model != null)
{


    <div class="row mt">
        <div class="col-md-12">
            <div class="content-panel">
                <table class="table table-striped table-advance table-hover">
                    <h4><i class="fa fa-angle-right"></i> List Of Projects</h4>
                    <hr>
                    <thead>
                        <tr>


                            <th><i class="fa fa-bookmark"></i> Project Name </th>





                            <th></th>
                        </tr>
                    </thead>

                    @foreach (var item in Model)
                    {

                        <tbody>
                            <tr>
                                <td><a href="basic_table.html#">@Html.DisplayFor(modelItem => item.Name)</a></td>


                                <td>
                                    <a href="@Url.Action("Edit"  , new { id = item.IdProject })">

                                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                                    </a>

                                    <a href="@Url.Action("Delete"  , new { id = item.IdProject })">

                                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>


                                    </a>

                                    <a href="@Url.Action("Details"  , new { id = item.IdProject})">

                                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                                    </a>


                                    <a href="@Url.Action("AllTasks" ,"Task" , new { idProject = item.IdProject})">

                                        <span class="label label-info label-mini">Tasks</span>
                                    </a>
                                </td>
                            </tr>




                        </tbody>
                    }


                </table>

            </div>
        </div>
    </div>



}
<a href="@Url.Action("ExportPDF" , "project")">
    <button type="button" class="btn btn-primary btn-lg btn-block">Export PDF</button>
</a>

PMT_DotNet/Web/Views/project/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<h2>UploadFile</h2>

@using (Html.BeginForm("UploadFile", "project", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        <input type="file" , name="file" id="file">

<input type="submit" value="Upload"/>


}